name: LINE Messaging API Push
on: [push] # 當你更新(Push)程式碼時就會自動觸發發送訊息

jobs:
  send-line-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install requests
        run: pip install requests

      - name: Run main.py
        run: python main.py
